#!/usr/bin/env node

const commands = require('./commands')

const userInputs = process.argv
const cmd = userInputs[2]
const id = userInputs[3]

switch (cmd) {
  case 'list':
    commands.list()
    break
  case 'done':
    commands.deleteTodo(id)
    //console.log(help)
    break

  default:
    console.log(`I don't understand that command: ${cmd}`)
}
