#!/usr/bin/env node

const commands = require('./commands')

const userInputs = process.argv
const cmd = userInputs[2]

switch (cmd) {
  case 'list':
    commands.list()
    break

  case 'done':
    commands.done(userInputs[3])
    break

  case 'update':
    commands.update(userInputs[3], userInputs[4])
    break

  case 'search':
    commands.search(userInputs[3])
    break

  default:
    console.log(`I don't understand that command: ${cmd}`)
}
