#!/usr/bin/env node

const commands = require('./commands')

const userInputs = process.argv
const cmd = userInputs[2]
const id = userInputs[3]
const task = userInputs [4]

switch (cmd) {
  case 'list':
    commands.list()
    break
  case 'done':
    commands.deleteTodo(id)  
    break
  case 'update':
    commands.updateTodo(id, task)
    break
  case 'search':
    commands.search(id, task)
    break
  default:
    console.log(`I don't understand that command: ${cmd}`)
}


//if user input string = string inside task return task